### ISSUE TITLE
Support for alerts

### ISSUE THREAD

**Issue by elblivion** [henrikhodne/go-librato#5]
Hi,

I've been playing with the Terraform provider you created and I'm interested in extending it (and therefore this lib) to support managing alerts, since we use Librato's alerting component a lot at Contentful. Do you have any pointers for me to get started, or know of any existing efforts to implement this?

Thanks!

**Comment by elblivion** [comment]
😢

**Comment by henrikhodne** [comment]
Hi! Sorry, I missed your first comment, my GitHub inbox had filled up quite a bit. I'm not really working much on this library right now, other things have taken priority, but if you want to work on a pull request for alerts I'd be happy to review it. It'd probably be best to look at the files like [spaces.go](https://github.com/henrikhodne/go-librato/blob/master/librato/spaces.go) or [metrics.go](https://github.com/henrikhodne/go-librato/blob/master/librato/metrics.go) and base the alerts API on that.
